alias nvtop="watch -d -n 0.5 nvidia-smi"
alias settings="env XDG_CURRENT_DESKTOP=GNOME gnome-control-center"
alias open="xdg-open"
alias r="radian"
alias pass="lpass show -Gp"
alias suspend="systemctl suspend"
alias sleep="systemctl suspend"
alias please="sudo"
alias passuio="lpass show -Gcp ocbe"
alias today="todoist list -f today"
alias todo="todoist list -f "$1""
alias med-biostat="ssh waldirln@login.uio.no -t ssh med-biostat"
alias copy="xclip -selection clipboard"
