alias nvtop="watch -d -n 0.5 nvidia-smi"
alias open="xdg-open"
alias r="~/venv/bin/radian"
alias python="bpython"
alias please="sudo"
alias smaug="ssh waldirln@login.uio.no"
alias mb="ssh waldirln@login.uio.no -t ssh med-biostat"
alias mb2="ssh waldirln@login.uio.no -t ssh med-biostat2"
alias copy="xclip -selection clipboard"
alias bt="bluetoothctl"
alias update="sudo nala update; sudo nala upgrade"
alias cleanR="sudo docker run --rm -ti r-base bash"
alias av="shutdown"
alias connect="nmcli connection up eduroam"
alias matlab="/usr/local/MATLAB/R2023b/bin/matlab -nodesktop -nosplash"
alias lstar="tar -ztvf"
alias copilot="gh copilot"
alias ls="eza"
alias pqp="fuck"
alias pushuio="uiosync.sh push"
alias pulluio="uiosync.sh pull"

# Common folders
alias work="cd $HOME/UiO/Projects"
alias sync="cd $HOME/Programs/syncconfig"
alias pump="cd $HOME/Dropbox/Fitness/workoutPlan"


