import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/Alabaster.dark.toml"
]

[font.normal]
family = "CommitMono Nerd Font"

[cursor]
blink_interval = 500

  [cursor.style]
  blinking = "On"

[window]
dynamic_title = false
