
[font.normal]
family = "CommitMono Nerd Font"

[cursor]
blink_interval = 500

  [cursor.style]
  blinking = "On"

[window]
dynamic_title = true
padding = {x = 5, y = 5}

[colors]
vi_mode_cursor = {text = "#000000", cursor = "#00FFFF"}

[general]
import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/Alabaster.dark.toml"
]

