# Source: https://starship.rs/config/
# Source for icons: https://www.nerdfonts.com/cheat-sheet

palette = 'uio'
format = """
[  ](bg:graa fg:svart)\
$directory\n
($git_branch $git_status$git_state)\
$character
"""

[palettes.uio]
roed = '#b60000'
svart = '#000000'
graa = '#b2b3b7'
blaa = '#3e31d6'
lysblaa = '#86a4f7'
blaatone = '#e6ecff'
groenn = '#2ec483'
roed_2 = '#dd0000'
lysroed = '#fb6666'
roedtone = '#fee0e0'
oransje = '#fea11b'
gul = '#fffea7'
# Source: https://www.uio.no/om/designmanual/profilelementer/fargepalett/index.html

[directory]
style = "bold fg:blaatone bg:roed"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Dropbox" = ""

[git_branch]
symbol = ""
style = "fg:blaatone"
format = '[$symbol $branch]($style)'

[git_status]
style = "bold lysroed"
modified = "($count)m"
staged = "($count)s"
deleted = "($count)d"
untracked = "($count)u"
renamed = "($count)r"
stashed = "(+ stash)"
format = '([\[$conflicted$stashed$deleted$renamed[$staged](bold oransje)[$modified](bold groenn)$typechanged[$untracked](bold lysblaa)$ahead_behind\]]($style) )'

[git_metrics]
disabled = false

[rlang]
symbol='󰟔'
detect_files=['DESCRIPTION']
style = "bg:#212736"
format = '[[ $symbol ](fg:#769ff0 bg:#212736)]($style)'

[character]
vimcmd_symbol = '[N](bold blue)'
vimcmd_replace_one_symbol = '[R](bold red)'
vimcmd_replace_symbol = '[R](bold magenta)'
vimcmd_visual_symbol = '[v](bold purple)'

