# Source: https://starship.rs/config/
# Source for icons: https://www.nerdfonts.com/cheat-sheet

palette = 'uio'
format = """
[  ](bg:graa fg:svart)\
$directory\n
($git_branch $git_status $git_state $git_metrics)\
$character
"""

[palettes.uio]
roed = '#b60000'
svart = '#000000'
graa = '#b2b3b7'
blaa = '#3e31d6'
lysblaa = '#86a4f7'
blaatone = '#e6ecff'
# Source: https://www.uio.no/om/designmanual/profilelementer/fargepalett/index.html

[directory]
style = "bold fg:blaatone bg:roed"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Dropbox" = ""

[git_branch]
symbol = ""
style = "fg:blaatone"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bold roed"
modified = "m$count"
staged = "s$count"
deleted = "d$count"
untracked = "u$count"
renamed = "r$count"
stashed = "(+ stash)"
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_metrics]
disabled = false

[rlang]
symbol='󰟔'
detect_files=['DESCRIPTION']
style = "bg:#212736"
format = '[[ $symbol ](fg:#769ff0 bg:#212736)]($style)'
