# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: !!null vim
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    iv: issue view
    il: issue list
    ei: issue edit
    li: issue list
    i: issue view --comments
    ie: issue edit
    rl: run list
    rlog: run view --log -j
    rw: run watch
    rv: run view
    prl: pr list
    prv: pr view
    ivw: issue view --web
    rc: run cancel
    icr: issue create
    icm: issue comment
    web: repo view --web
    it: issue view --json "title"
    rvl: run view --log-failed --job
    contrib: graph -i -p %20 -s blue
    plot: contribs --glyph block --xgap --labels
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
