#!/usr/bin/bash
version="0.4.1 under GPLv3 (https://choosealicense.com/licenses/gpl-3.0/)"

usage() {
    cat << EOU
Usage:
    copy2med [--from] FILE
    copy2med [--from] FILE -u USERNAME
    copy2med -h | --help
    copy2med --version

Simplifies file transfer between a local machine and the med-biostat servers

Arguments:
    FILE       file to be transferred
    USERNAME   username on the remote server (will be prompted if not provided)

Options:
    --from     copy from remote to local
    -u         username on the remote server (will be prompted if not provided)
    -h --help  Print this help and exit
    --version  Print version and exit
EOU
}

# Setting variables
help=$(usage)
servername="med-biostat2"

# Processing options
eval "$(docopts -A ARGS -h "$help" -V "$version" : "$@")"
file="${ARGS['FILE']}"

# Retrieving username on remote
if [ -n "$UIO_USERNAME" ]; then
    username="$UIO_USERNAME"
elif [ -z "${ARGS['USERNAME']}" ]; then
	echo -n "Username on remote: "
	read username
else
	username="${ARGS['USERNAME']}"
fi

# Origin and destination depend on direction
host="$username@login.uio.no"
server="$username@$servername.hpc.uio.no:/data/$username"
scp_args="$host $file $server"
if [ "${ARGS['--from']}" = true ]; then
    scp_args="$host $server/$file ."
fi

# Copying files
scp -J $scp_args

exit $?
