#!/usr/bin/bash
#
# Searches for a package on APT, Snap and Flatpak repositories

version="0.0.0 licensed under GPLv3"

usage() {
  less << EOU
Usage:
  $(basename $0) PKG
  $(basename $0) -h | --help
  $(basename $0) --version

Search for a package on APT, Snap, and Flatpak repositories.

Options:
  -h --help     Show this help message and exit
  --version     Show version and exit

Examples:
  $(basename $0) todoist

EOU
}

# Check if docopts is installed
if ! command -v docopts &> /dev/null; then
  echo "Error: docopts is not installed."
  exit 2
fi

eval "$(docopts -A ARGS -h "$(usage)" -V "$version" : "$@")"

pkg="${ARGS['PKG']}"

echo "Searching apt"
echo

nala search "$pkg"

echo
echo "Searching snap"
echo

snap search "$pkg"

echo
echo "Searching flatpak"
echo

flatpak search "$pkg"
